'use strict'

const CREDITQ_KNOWLEDGE = {
  company: {
    name: 'CreditQ',
    tagline: "India's first B2B Business Credit Management & Information Platform",
    target: 'GST-registered MSMEs, suppliers, B2B sellers extending credit to buyers',
    coreProblem: 'Businesses lose crores to payment defaults from unknown or unreliable buyers',
    solution: 'Check buyer creditworthiness BEFORE transacting, report defaulters, recover dues',
    requirement: 'Must be GST-registered to use CreditQ services',
    keyStats: [
      "India's first B2B credit bureau for MSMEs",
      'Covers structured settlement + legal notice delivery',
      'Automated payment reminders via SMS, call, email, WhatsApp',
    ],
  },

  services: {
    cir: {
      name: 'Credit Information Report (CIR)',
      what: 'Full credit profile of any GST-registered business in India',
      includes: ['Payment history', 'Default records', 'Director details', 'GST verification', 'Trade references'],
      purpose: 'Know WHO you are selling to before extending any credit',
    },
    defaulterReporting: {
      name: 'Report Business Defaulters',
      what: 'Add non-paying businesses to a national defaulter database',
      effect: 'Defaulter gets flagged across all suppliers — creates immediate settlement pressure',
      settlement: 'Structured settlement process: defaulter pays to get removed from database',
    },
    verifications: {
      types: ['Aadhaar', 'PAN', 'GST', 'Background check', 'Police verification'],
      availability: 'SILVER plan and above',
    },
    reminders: {
      channels: ['SMS', 'Call', 'Email', 'WhatsApp'],
      availability: 'SILVER plan and above',
      benefit: 'Automated follow-ups — zero manual collection effort',
    },
    legalSupport: {
      physicalNotice: 'Registered post notice to defaulter — creates legal record',
      directorNotice: 'Legal notice sent to ALL directors of defaulting company',
      availability: 'DIAMOND: 1/month | ENTERPRISE: 2/month | ENTERPRISE PRO+: 2-3/month',
    },

    businessCreditManagement: {
      name: 'Business Credit Management (BCM)',
      what: 'Digitizes accounts-receivable management with Tally/ERP integration',
      integration: ['Tally', 'ERP systems'],
      features: [
        'Auto-syncs invoices and payment schedules from accounting software',
        'Auto-acceptance of invoices by buyers, digital invoice sharing',
        'Scheduled SMS/email reminders before and after due dates',
        'Direct defaulter reporting from dashboard when due date passes unpaid',
        'Central credit ledger — all credit transactions in one digital dashboard',
      ],
      benefit: 'Zero manual follow-up — system tracks, reminds, escalates automatically',
      availability: 'SILVER and above',
    },

    msme: {
      name: 'MSME Solutions',
      what: "Support for India's 60M+ MSMEs — credit reports, scores, registration assistance",
      features: [
        'MSME Credit Report: payment trends, repayment history, credit health metrics, risk insights',
        'MSME Credit Score: reflects payment behavior, improves credibility with lenders and partners',
        'MSME Registration Assistance: simplified digital process for all paperwork and compliance',
        'Expert guidance on subsidies, tax benefits, and government MSME schemes',
        'Sector insights: credit health trends and opportunities for MSMEs',
      ],
      benefit: 'Helps MSMEs demonstrate creditworthiness for loans, government schemes, and B2B partnerships',
    },

    settlement: {
      name: 'Scope of Settle Payment',
      what: 'Tools to manage, track, and document payment settlement with defaulters',
      process: [
        'List defaulter on CreditQ with evidence (ledger + CA certificate)',
        'Negotiate directly outside platform — full payment or instalments',
        'Mark as "settled" on CreditQ once payment received',
        'Settlement record stays visible for transparency — accountability maintained',
      ],
      keyFact: 'After settlement, defaulter remains on list (transparency) but credit rating stops dropping',
      reminders: 'Auto SMS/WhatsApp/email/call reminders apply pressure without manual effort',
      benefit: 'Turns "I will pay later" into actual payment — restores working capital fast',
    },
  },

  plans: [
    {
      name: 'BASIC',
      price: 0,
      validity: 'Limited access',
      walletPoints: 0,
      cirCost: 2000,
      addBusinessCost: 0,
      maxReportable: 'Limited',
      keyLimitations: ['No verifications', 'No dispute management', 'No legal help', 'No reminders'],
      pitch: 'Free to start — but cannot protect business properly without an upgrade',
    },
    {
      name: 'SILVER',
      price: 10000,
      validity: '1 year',
      walletPoints: 0,
      cirCost: 1800,
      addBusinessCost: 5000,
      addBusinessDiscount: '50% off',
      maxReportable: 'Up to ₹2 lakhs',
      referralEarn: 500,
      referralDiscount: 500,
      includes: ['All verifications', 'Dispute management', 'Payment reminders', 'Invoice auto-sharing'],
      pitch: 'Entry-level protection — ideal for small suppliers with a few key buyers',
    },
    {
      name: 'GOLD',
      price: 25000,
      validity: '1 year',
      walletPoints: 80000,
      cirCost: 1500,
      addBusinessCost: 8000,
      addBusinessDiscount: '60% off',
      addBusinessWalletReturn: 32000,
      maxReportable: 'Up to ₹10 lakhs',
      referralEarn: 500,
      referralDiscount: 500,
      includes: ['Everything in SILVER', '80K wallet points upfront', 'Faster recovery tools'],
      pitch: 'Best for growing businesses with 10-50 buyers — wallet points offset your costs',
    },
    {
      name: 'DIAMOND',
      price: 50000,
      validity: '2 years',
      walletPoints: 250000,
      cirCost: 1300,
      addBusinessCost: 15000,
      addBusinessDiscount: '70% off',
      addBusinessWalletReturn: 75000,
      maxReportable: 'Up to ₹25 lakhs',
      referralEarn: 2000,
      referralDiscount: 1000,
      includes: ['Dedicated relationship manager', '1 physical notice/month', '2-year coverage'],
      pitch: 'Most popular — 2 years for ₹20K. Dedicated RM. Best value per rupee.',
    },
    {
      name: 'ENTERPRISE',
      price: 70000,
      validity: '5 years',
      walletPoints: 700000,
      cirCost: 1200,
      addBusinessCost: 20000,
      addBusinessDiscount: '80% off',
      addBusinessWalletReturn: 140000,
      maxReportable: 'Up to ₹50 lakhs',
      referralEarn: 3000,
      referralDiscount: 1500,
      includes: ['Personal legal assistance', '2 physical notices/month', 'All director legal notices', '5-year coverage'],
      pitch: 'Serious businesses only — ₹14K/year for 5 years. One recovery pays for this 10x.',
    },
    {
      name: 'ENTERPRISE PRO',
      price: 150000,
      validity: '7 years',
      walletPoints: 2400000,
      cirCost: 1000,
      addBusinessCost: 25000,
      addBusinessDiscount: '92% off',
      addBusinessWalletReturn: 200000,
      maxReportable: 'No limit',
      referralEarn: 5000,
      referralDiscount: 2500,
      includes: ['Everything in ENTERPRISE', 'No reportable limit', '7-year coverage', 'Massive wallet points'],
      pitch: 'Large-scale B2B operations — ₹21K/year for 7 years. Enterprise-grade protection.',
    },
    {
      name: 'LIFETIME',
      price: 500000,
      validity: 'Unlimited',
      walletPoints: 'Unlimited',
      cirCost: 1000,
      addBusinessCost: 200000,
      addBusinessDiscount: '90% off',
      addBusinessWalletReturn: 'Unlimited',
      maxReportable: 'No limit',
      referralEarn: 5000,
      referralDiscount: 5000,
      includes: ['Everything, forever', '3 physical notices/month', 'Unlimited wallet points', 'Zero recurring cost'],
      pitch: 'Pay once, never again. Your business is protected for life.',
    },
  ],

  defaulterProcess: {
    requiredDocuments: [
      'Up-to-date ledger of transactions with the defaulter',
      'Chartered Accountant (CA) certificate with UDIN number proving the debt',
    ],
    panFallback: 'Defaulter has no GSTIN? Report using their PAN number instead',
    reviewTime: 'CreditQ verifies and publishes within 2 working days',
    freeForMembers: true,
    defaulterNotification: 'CreditQ notifies the defaulter via email, SMS, and WhatsApp upon being reported',
    postSettlement: 'After settlement, defaulter stays on list for transparency but credit rating stops dropping',
    supportContact: 'support@creditq.in for disputes or listing issues',
  },

  contact: 'support@creditq.in',

  salesPlaybook: {
    openingHook: "Har saal ek MSME average ₹8-12 lakh bad debts mein khota hai. CreditQ isko rokne ke liye exist karta hai.",

    discoveryQuestions: [
      'How many buyers are you currently extending credit to?',
      'Have you ever had a buyer default or significantly delay payment?',
      'What do you currently do when a buyer stops paying?',
      'How do you verify a new buyer before extending credit?',
      'What is the largest single bad debt you have faced in the last 3 years?',
    ],

    painPoints: {
      defaulters: 'With defaulter reporting, we put pressure on them without court. Most settle within 30 days.',
      unknown_buyers: 'Our CIR gives you their full payment history before you ship the first invoice.',
      recovery: 'We do not just flag — we help recover. Physical notices, legal support, structured settlement.',
      time_waste: 'Automated reminders follow up for you — SMS, call, WhatsApp — zero manual effort.',
      cash_flow: 'One CIR before extending credit costs less than one defaulter. Always.',
    },

    objectionHandlers: {
      too_expensive: "What did your last bad debt cost you? ₹10,000 for a year of SILVER is nothing against one defaulter. And wallet points recover most of that cost back.",
      already_have_process: "Does your current process give you a defaulter's history across all of India's suppliers? Or automated legal notices? That is what CreditQ adds on top.",
      will_think_about_it: "Of course. But defaulters do not wait. Every day without checking, you are extending credit on trust. Start on BASIC — it is free. See the platform yourself.",
      not_needed_yet: "You have not needed it yet — until you do. Businesses who call us after a default wish they had joined before. Prevention costs 10x less than cure.",
      need_to_discuss_partner: "Absolutely. While you discuss — shall I pull a CIR on one of your current buyers? It is free on BASIC. Your partner sees exactly what CreditQ gives you.",
      competitor_exists: "Good — you are researching. Tell me which one and I will tell you exactly what we do that they do not. Physical notice delivery and settlement in one platform — nobody else has that.",
      no_time: "This takes 10 minutes to set up. I will walk you through it. The question is not time — it is whether you can afford the next default.",
    },

    closeScripts: {
      softClose: 'Based on what you have told me, DIAMOND fits perfectly — 2 years, dedicated RM, covers up to ₹25 lakhs. Shall I walk you through onboarding?',
      urgencyClose: 'Promotional pricing on DIAMOND will not last. If you are serious about protecting your business, this week is the time.',
      assumptiveClose: 'Let me get your GST number and your account is active in 10 minutes. What is the best email for subscription details?',
      fenceSitterClose: 'You have already told me you have had payment issues. You know you need this. SILVER to start, or DIAMOND for full coverage — which feels right?',
      roiClose: 'If CreditQ helps you avoid even ONE bad debt this year, what does that save you? ₹2 lakhs? ₹5 lakhs? SILVER costs ₹10,000. That is a 20x return minimum.',
    },

    urgencyTriggers: [
      'Limited-time pricing on DIAMOND and ENTERPRISE',
      'GST-registered businesses who join now get priority onboarding',
      'Every month without CreditQ is a month of unprotected credit exposure',
    ],

    hinglishPhrases: [
      "Dekhiye, ek defaulter ne aapka ₹10 lakh rok liya — CreditQ se usko report karo, 30 din mein mostly settle ho jaata hai.",
      "Aap kitne buyers ko credit de rahe ho abhi? Kabhi unka background check kiya?",
      "Bilkul samajh aaya — lekin yeh socho: ek bhi bad debt se jo loss hota hai, woh SILVER plan ki poori cost se zyada hai.",
      "Bhai, sirf GST number chahiye — 10 minute mein account active ho jaata hai.",
      "DIAMOND plan sabse best value hai — 2 saal ke liye, dedicated relationship manager, ₹25 lakh tak protection.",
      "Apne business ko protect karo — CreditQ India ka pehla B2B credit bureau hai.",
      "Suno, competitor ke paas settlement track karne aur physical notice bhejne ka feature nahi — sirf CreditQ mein hai yeh.",
      "Aapne khud bola na ki ek buyer ne paisa rok liya — wahi toh hum solve karte hain.",
    ],
  },
}

module.exports = { CREDITQ_KNOWLEDGE }
